const multiplayerTypes = {
    SET_CURRENT_NAME: "SET_CURRENT_NAME",
    SET_CURRENT_ID: "SET_CURRENT_ID",
    SET_PLAYER_2: "SET_PLAYER_2",
    SET_WEAPON: "SET_WEAPON",
    UPDATE_BOARD: "UPDATE_BOARD",
    SET_CHANCE: "SET_CHANCE",
    RESET_MULTIPLAYER: "RESET_MULTIPLAYER",
    SET_ROOM_ID: "SET_ROOM_ID",
    SET_RESULT: "SET_RESULT",
    UPDATE_STATE: "UPDATE_STATE",
    NEW_GAME: "NEW_GAME"
};

export default multiplayerTypes;